/** @format */

import { Jost } from "next/font/google";
import "./globals.css";
import "boxicons/css/boxicons.min.css";

const jost = Jost({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-jost",
	display: "swap",
	subsets: ["latin"],
});

export const metadata = {
	title: "Fortune",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${jost.variable}`}>{children}</body>
		</html>
	);
}
